//
//  NutrimentsFactKeys.swift
//  FoodViewer
//
//  Created by arnaud on 21/12/16.
//  Copyright © 2016 Hovering Above. All rights reserved.
//

import Foundation

struct NutrimentsFactKeys {
    
    static let EnergyKey = "Energy"
    static let FatKey = "Fat"
    static let MonounsaturatedFatKey = "Monounsaturated fat"
    static let PolyunsaturatedFatKey = "Polyunsaturated fat"
    static let SaturatedFatKey = "Saturated fat"
    static let Omega3FatKey = "Omega-3 fat"
    static let Omega6FatKey = "Omega-6 fat"
    static let Omega9FatKey = "Omega-9 fat"
    static let TransFatKey = "Trans fat"
    static let CholesterolKey = "Cholesterol"
    static let CarbohydratesKey = "Carbohydrates"
    static let SugarsKey = "Sugars"
    static let SucroseKey = "Sucrose"
    static let GlucoseKey = "Glucose"
    static let FructoseKey = "Fructose"
    static let LactoseKey = "Lactose"
    static let MaltoseKey = "Maltose"
    static let PolyolsKey = "Polyols"
    static let MaltodextrinsKey = "Maltodextrins"
    static let FiberKey = "Fiber"
    static let ProteinsKey = "Proteins"
    static let AlcoholKey = "Alcohol"
    static let SodiumKey = "Sodium"
    static let SaltKey = "Salt"
    
    static let BiotinKey = "Biotin"
    static let CaseinKey = "Casein"
    static let SerumProteinsKey = "Serum proteins"
    static let NucleotidesKey = "Nucleotides"
    static let StarchKey = "Starch"
    
    static let AlphaLinolenicAcidKey = "Alpha-linolenic acid"
    static let ArachidicAcidKey = "Arachidic acid"
    static let ArachidonicAcidKey = "Arachidonic acid"
    static let BehenicAcidKey = "Behenic acid"
    static let ButyricAcidKey = "Butyric acid"
    static let CapricAcidKey = "Capric acid"
    static let CaproicAcidKey = "Caproic acid"
    static let CaprylicAcidKey = "Caprylic-acid"
    static let CeroticAcidKey = "Cerotic acid"
    static let DihomoGammaLinolenicAcidKey = "Dihomo-gamma-linolenic acid"
    static let DocosahexaenoicAcidKey = "Docosahexaenoic acid"
    static let EicosapentaenoicAcidKey = "Eicosapentaenoic acid"
    static let ElaidicAcidKey = "Elaidic acid"
    static let ErucicAcidKey = "Erucic acid"
    static let GammaLinolenicAcidKey = "Gamma-linolenic acid"
    static let GondoicAcidKey = "Gondoic acid"
    static let LauricAcidKey = "Lauric acid"
    static let LignocericAcidKey = "Lignoceric acid"
    static let LinoleicAcidKey = "Linoleic acid"
    static let MeadAcidKey = "Mead acid"
    static let MelissicAcidKey = "Melissic acid"
    static let MontanicAcidKey = "Montanic acid"
    static let MyristicAcidKey = "Myristic acid"
    static let NervonicAcidKey = "Nervonic acid"
    static let PalmiticAcidKey = "Palmitic acid"
    static let PantothenicAcidKey = "Pantothenic acid"
    static let StearicAcidKey = "Stearic acid"
    static let VoleicAcidKey = "Voleic acid"
    
    static let VitaminAKey = "Vitamin A"
    static let VitaminB1Key = "Vitamin B1"
    static let VitaminB2Key = "Vitamin B2"
    static let VitaminPPKey = "Vitamin PP"
    static let VitaminB6Key = "Vitamin B6"
    static let VitaminB9Key = "Vitamin B9"
    static let VitaminB12Key = "Vitamin B12"
    static let VitaminCKey = "Vitamin C"
    static let VitaminDKey = "Vitamin D"
    static let VitaminEKey = "Vitamin E"
    static let VitaminKKey = "Vitamin K"
    
    static let CalciumKey = "Calcium"
    static let ChlorideKey = "Chloride"
    static let ChromiumKey = "Chromium"
    static let CopperKey = "Copper"
    static let BicarbonateKey = "Bicarbonate"
    static let FluorideKey = "Fluoride"
    static let IodineKey = "Iodine"
    static let IronKey = "Iron"
    static let MagnesiumKey = "Magnesium"
    static let ManganeseKey = "Manganese"
    static let MolybdenumKey = "Molybdenum"
    static let PhosphorusKey = "Phosphorus"
    static let PotassiumKey = "Potassium"
    static let SeleniumKey = "Selenium"
    static let SilicaKey = "Silica"
    static let ZincKey = "Zinc"
    
    static let CaffeineKey = "Caffeine"
    static let TaurineKey = "Taurine"
    
    static let PhKey = "ph"
    static let CacaoKey = "Cacao Min."
}
