//
//  NutrimentsFactKeys.swift
//  FoodViewer
//
//  Created by arnaud on 21/12/16.
//  Copyright © 2016 Hovering Above. All rights reserved.
//
//  These are the possible keys for the nutriments that are used in the OFF taxonomies
import Foundation

enum NutrimentsFactKeys: String {
    
    typealias RawValue = String
    
    case addedSugarsKey = "added-sugars"
    case alcoholKey = "alcohol"
    case alphaLinolenicAcidKey = "alpha-linolenic-acid"
    case arachidicAcidKey = "arachidic-acid"
    case arachidonicAcidKey = "arachidonic-acid"
    case behenicAcidKey = "behenic-acid"
    case bicarbonateKey = "bicarbonate"
    case biotinKey = "biotin"
    case butyricAcidKey = "butyric-acid"
    case cacaoKey = "cocoa"
    case caffeineKey = "caffeine"
    case calciumKey = "calcium"
    case capricAcidKey = "capric-acid"
    case caproicAcidKey = "caproic-acid"
    case caprylicAcidKey = "caprylic-acid"
    case carbohydratesKey = "carbohydrates"
    case caseinKey = "casein"
    case chlorideKey = "chloride"
    case chromiumKey = "chromium"
    case ceroticAcidKey = "cerotic-acid"
    case cholesterolKey = "cholesterol"
    case copperKey = "copper"
    case dihomoGammaLinolenicAcidKey = "dihomo-gamma-linolenic-acid"
    case docosahexaenoicAcidKey = "docosahexaenoic-acid"
    case eicosapentaenoicAcidKey = "eicosapentaenoic-acid"
    case elaidicAcidKey = "elaidic-acid"
    case energyKey = "energy"
    case energyFromFatKey = "energy-from-fat"
    case erucicAcidKey = "erucic-acid"
    case fatKey = "fat"
    case fiberKey = "fiber"
    case fluorideKey = "fluoride"
    case fructoseKey = "fructose"
    case gammaLinolenicAcidKey = "gamma-linolenic-acid"
    case glucoseKey = "glucose"
    case gondoicAcidKey = "gondoic-acid"
    case iodineKey = "iodine"
    case ironKey = "iron"
    case lactoseKey = "lactose"
    case lauricAcidKey = "lauric-acid"
    case lignocericAcidKey = "lignoceric-acid"
    case linoleicAcidKey = "linoleic-acid"
    case magnesiumKey = "magnesium"
    case maltodextrinsKey = "maltodextrins"
    case maltoseKey = "maltose"
    case manganeseKey = "manganese"
    case meadAcidKey = "mead-acid"
    case melissicAcidKey = "melissic-acid"
    case molybdenumKey = "molybdenum"
    case monounsaturatedFatKey = "monounsaturated-fat"
    case montanicAcidKey = "montanic-acid"
    case myristicAcidKey = "myristic-acid"
    case nervonicAcidKey = "nervonic-acid"
    case nucleotidesKey = "nucleotides"
    case omega3FatKey = "omega-3-fat"
    case omega6FatKey = "omega-6-fat"
    case omega9FatKey = "omega-9-fat"
    case palmiticAcidKey = "palmitic-acid"
    case pantothenicAcidKey = "pantothenic-acid"
    case phKey = "ph"
    case phosphorusKey = "phosphorus"
    case polyolsKey = "polyols"
    case polyunsaturatedFatKey = "polyunsaturated-fat"
    case potassiumKey = "potassium"
    case proteinsKey = "proteins"
    case saltKey = "salt"
    case saturatedFatKey = "saturated-fat"
    case seleniumKey = "selenium"
    case serumProteinsKey = "serum-proteins"
    case silicaKey = "silica"
    case sodiumKey = "sodium"
    case sucroseKey = "sucrose"
    case sugarsKey = "sugars"
    case starchKey = "starch"
    case stearicAcidKey = "stearic-acid"
    case taurineKey = "taurine"
    case transFatKey = "trans-fat"
    case voleicAcidKey = "voleic-acid"
    case vitaminAKey = "vitamin-a"
    case vitaminDKey = "vitamin-d"
    case vitaminEKey = "vitamin-e"
    case vitaminKKey = "vitamin-k"
    case vitaminCKey = "vitamin-c"
    case vitaminB1Key = "vitamin-b1"
    case vitaminB2Key = "vitamin-b2"
    case vitaminPPKey = "vitamin-pp"
    case vitaminB6Key = "vitamin-b6"
    case vitaminB9Key = "vitamin-b9"
    case vitaminB12Key = "vitamin-b12"
    case zincKey = "zinc"
}
